apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: simple
        tier: backend
        type: api
    spec:
      restartPolicy: Always
      containers:
      - name: simple-api
        image: varsoft/simple-api:dev
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 1500
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /health
            port: 1500
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: simple-api
              key: node.env
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: simple-api
              key: node.port
        ports:
          - containerPort: 1500