apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-api
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - simple-api.sandbox.fieldinsight.co
    secretName: simple-api-tls
  rules:
  - host: simple-api.sandbox.fieldinsight.co
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-api
          servicePort: 1500
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: simple-api
  namespace: sandbox
spec:
  secretName: simple-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: simple-api.sandbox.fieldinsight.co
  acme:
    config:
    - http01:
        ingress: simple-api
      domains:
      - simple-api.sandbox.fieldinsight.co