apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-api
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: simple-api.sandbox.fieldinsight.co
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-api
          servicePort: 1500