apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-api
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: simple-api.cloud.varsoftng.com
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-api
          servicePort: 1500
