jobs:
  build:
    machine: true
#    docker:
#      - image: 'circleci/node:11'
    steps:
      - checkout
      # Docker login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t varsoft/simple-api:$CIRCLE_BRANCH .
      # deploy the image
      - run: docker push varsoft/simple-api:$CIRCLE_BRANCH

      - slack/status:
          mentions: 'shawlz'

#release-branch-workflow:
#  jobs:
#    - build
#    - request-testing:
#        type: approval
#        requires:
#          - build
#    - deploy-aws:
#        requires:
#          - request-testing
orbs:
  slack: circleci/slack@3.2.0
version: 2.1