jobs:
  build:
    machine: true
    steps:
      - checkout
      # Docker login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t varsoft/simple-api:$(git rev-parse HEAD) .
      # deploy the image
      - run: docker push varsoft/simple-api:$(git rev-parse HEAD)
      - slack/approval:
          message: Pending approval of build
          mentions: 'shawlz'
  deploy:
    machine: true
    steps:
      - checkout
      - kubernetes/install
      - run:
          name: Kubeconfig
          command: |-
            kubectl config set-credentials circleci-sa --token=$CIRCLECI_PIPELINE_SA_TOKEN
            kubectl config set-cluster --server=$K8S_CLUSTER_IP --insecure-skip-tls-verify=true
            kubectl config set-context k8s-cluster-context --cluster=k8s-cluster --user=circleci-sa
            kubectl config use-context k8s-cluster-context
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/configmaps/development.yaml
          namespace: sandbox
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/ingress/development.yaml
          namespace: sandbox
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/services/services.yaml
          namespace: sandbox
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment/deployments/deployment.yaml
          resource-name: deployment/simple-api
          namespace: sandbox
          show-kubectl-command: true
      - slack/status:
          mentions: 'shawlz'
workflows:
  version: 2
  dev-branch-workflow:
    jobs:
      - build
      - request-approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - request-approval
orbs:
  slack: circleci/slack@3.2.0
  kubernetes: circleci/kubernetes@0.3.0
version: 2.1
