jobs:
  build:
    machine: true
    steps:
      - checkout
      # Docker login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t varsoft/simple-api:$(git rev-parse HEAD) .
      # deploy the image
      - run: docker push varsoft/simple-api:$(git rev-parse HEAD)
      - slack/approval:
          message: Pending approval of build
          mentions: 'shawlz'
  deploy:
    machine: true
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_ENCODED
      - run: echo $KUBECONFIG
      - run: cat $HOME/.kube/config
      - run: kubectl get pods --namespace kube-system
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/configmaps/development.yaml
          namespace: default
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/ingress/development.yaml
          namespace: default
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/services/services.yaml
          namespace: default
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment/deployments/deployment.yaml
          resource-name: deployment/simple-api
          namespace: default
          show-kubectl-command: true
#       - slack/status:
#           mentions: 'shawlz'
workflows:
  version: 2
  dev-branch-workflow:
    jobs:
#       - build
#       - request-approval:
#           type: approval
#           requires:
#             - build
      - deploy
#       - deploy: 
#           requires:
#             - request-approval
orbs:
  slack: circleci/slack@3.4.1
  kubernetes: circleci/kubernetes@0.10.1
version: 2.1
