jobs:
  build:
    docker:
      - image: 'circleci/classic:201808-01'
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: '@sajayi'
          only_for_branches: only_for_branches
          webhook: webhook
orbs:
  slack: circleci/slack@3.2.0
version: 2.1