jobs:
  build:
    machine: true
    steps:
      - checkout
      # Docker login
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # build the application image
      - run: docker build -t varsoft/simple-api:$(git rev-parse HEAD) .
      # deploy the image
      - run: docker push varsoft/simple-api:$(git rev-parse HEAD)
      - slack/approval:
          message: Pending approval of build
          mentions: 'shawlz'
  deploy:
    machine: true
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_ENCODED
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/configmaps/development.yaml
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/ingress/development.yaml
          namespace: sandbox
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/services/services.yaml
          namespace: sandbox
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment/deployments/deployment.yaml
          namespace: sandbox
          resource-name: deployment/simple-api
          show-kubectl-command: true
      - slack/status:
          mentions: 'shawlz'
workflows:
  version: 2
  dev-branch-workflow:
    jobs:
      - build
      - request-approval:
          type: approval
          requires:
            - build
      - deploy: 
          requires:
            - request-approval
orbs:
  slack: circleci/slack@3.4.1
  kubernetes: circleci/kubernetes@0.10.1
version: 2.1
