jobs:
  build:
    docker:
      - image: 'circleci/node:11'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd application && yarn install
      - run
          name: Build Image
          command: docker build .
      - slack/status:
          mentions: 'shawlz'
#release-branch-workflow:
#  jobs:
#    - build
#    - request-testing:
#        type: approval
#        requires:
#          - build
#    - deploy-aws:
#        requires:
#          - request-testing
orbs:
  slack: circleci/slack@3.2.0
version: 2.1